/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SessionToken = IDL.Text;
export const AdminLoginResult = IDL.Variant({
  'ok' : SessionToken,
  'err' : IDL.Text,
});
export const UpdateProfileInput = IDL.Record({
  'name' : IDL.Text,
  'address' : IDL.Text,
  'mobile' : IDL.Text,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const Student = IDL.Record({
  'prn' : IDL.Text,
  'principal' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'mobile' : IDL.Text,
});
export const UpdateResult = IDL.Variant({ 'ok' : Student, 'err' : IDL.Text });
export const DeleteResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const RegisterInput = IDL.Record({
  'prn' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'mobile' : IDL.Text,
  'hashedPassword' : IDL.Text,
});
export const RegisterResult = IDL.Variant({ 'ok' : Student, 'err' : IDL.Text });

export const idlService = IDL.Service({
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [AdminLoginResult], []),
  'adminUpdateStudent' : IDL.Func(
      [SessionToken, IDL.Text, UpdateProfileInput],
      [UpdateResult],
      [],
    ),
  'deleteStudent' : IDL.Func([SessionToken, IDL.Text], [DeleteResult], []),
  'getAllStudents' : IDL.Func(
      [SessionToken, IDL.Nat, IDL.Nat],
      [IDL.Vec(Student)],
      [],
    ),
  'getMyProfile' : IDL.Func([], [IDL.Opt(Student)], ['query']),
  'registerStudent' : IDL.Func([RegisterInput], [RegisterResult], []),
  'searchStudents' : IDL.Func([SessionToken, IDL.Text], [IDL.Vec(Student)], []),
  'updateMyProfile' : IDL.Func([UpdateProfileInput], [UpdateResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SessionToken = IDL.Text;
  const AdminLoginResult = IDL.Variant({
    'ok' : SessionToken,
    'err' : IDL.Text,
  });
  const UpdateProfileInput = IDL.Record({
    'name' : IDL.Text,
    'address' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const Student = IDL.Record({
    'prn' : IDL.Text,
    'principal' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const UpdateResult = IDL.Variant({ 'ok' : Student, 'err' : IDL.Text });
  const DeleteResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const RegisterInput = IDL.Record({
    'prn' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'mobile' : IDL.Text,
    'hashedPassword' : IDL.Text,
  });
  const RegisterResult = IDL.Variant({ 'ok' : Student, 'err' : IDL.Text });
  
  return IDL.Service({
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [AdminLoginResult], []),
    'adminUpdateStudent' : IDL.Func(
        [SessionToken, IDL.Text, UpdateProfileInput],
        [UpdateResult],
        [],
      ),
    'deleteStudent' : IDL.Func([SessionToken, IDL.Text], [DeleteResult], []),
    'getAllStudents' : IDL.Func(
        [SessionToken, IDL.Nat, IDL.Nat],
        [IDL.Vec(Student)],
        [],
      ),
    'getMyProfile' : IDL.Func([], [IDL.Opt(Student)], ['query']),
    'registerStudent' : IDL.Func([RegisterInput], [RegisterResult], []),
    'searchStudents' : IDL.Func(
        [SessionToken, IDL.Text],
        [IDL.Vec(Student)],
        [],
      ),
    'updateMyProfile' : IDL.Func([UpdateProfileInput], [UpdateResult], []),
  });
};

export const init = ({ IDL }) => { return []; };