/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AdminLoginResult = { 'ok' : SessionToken } |
  { 'err' : string };
export type DeleteResult = { 'ok' : null } |
  { 'err' : string };
export interface RegisterInput {
  'prn' : string,
  'name' : string,
  'email' : string,
  'address' : string,
  'mobile' : string,
  'hashedPassword' : string,
}
export type RegisterResult = { 'ok' : Student } |
  { 'err' : string };
export type SessionToken = string;
export interface Student {
  'prn' : string,
  'principal' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'email' : string,
  'address' : string,
  'mobile' : string,
}
export type Timestamp = bigint;
export interface UpdateProfileInput {
  'name' : string,
  'address' : string,
  'mobile' : string,
}
export type UpdateResult = { 'ok' : Student } |
  { 'err' : string };
export type UserId = Principal;
export interface _SERVICE {
  'adminLogin' : ActorMethod<[string, string], AdminLoginResult>,
  'adminUpdateStudent' : ActorMethod<
    [SessionToken, string, UpdateProfileInput],
    UpdateResult
  >,
  'deleteStudent' : ActorMethod<[SessionToken, string], DeleteResult>,
  'getAllStudents' : ActorMethod<
    [SessionToken, bigint, bigint],
    Array<Student>
  >,
  'getMyProfile' : ActorMethod<[], [] | [Student]>,
  'registerStudent' : ActorMethod<[RegisterInput], RegisterResult>,
  'searchStudents' : ActorMethod<[SessionToken, string], Array<Student>>,
  'updateMyProfile' : ActorMethod<[UpdateProfileInput], UpdateResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];