/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type UserId = Principal;
export type Timestamp = bigint;
export type RegisterResult = {
    __kind__: "ok";
    ok: Student;
} | {
    __kind__: "err";
    err: string;
};
export interface UpdateProfileInput {
    name: string;
    address: string;
    mobile: string;
}
export type SessionToken = string;
export interface RegisterInput {
    prn: string;
    name: string;
    email: string;
    address: string;
    mobile: string;
    hashedPassword: string;
}
export type DeleteResult = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export type UpdateResult = {
    __kind__: "ok";
    ok: Student;
} | {
    __kind__: "err";
    err: string;
};
export type AdminLoginResult = {
    __kind__: "ok";
    ok: SessionToken;
} | {
    __kind__: "err";
    err: string;
};
export interface Student {
    prn: string;
    principal: UserId;
    name: string;
    createdAt: Timestamp;
    email: string;
    address: string;
    mobile: string;
}
export interface backendInterface {
    adminLogin(email: string, hashedPassword: string): Promise<AdminLoginResult>;
    adminUpdateStudent(token: SessionToken, prn: string, input: UpdateProfileInput): Promise<UpdateResult>;
    deleteStudent(token: SessionToken, prn: string): Promise<DeleteResult>;
    getAllStudents(token: SessionToken, offset: bigint, limit: bigint): Promise<Array<Student>>;
    getMyProfile(): Promise<Student | null>;
    registerStudent(input: RegisterInput): Promise<RegisterResult>;
    searchStudents(token: SessionToken, searchQuery: string): Promise<Array<Student>>;
    updateMyProfile(input: UpdateProfileInput): Promise<UpdateResult>;
}
import type { AdminLoginResult as _AdminLoginResult, DeleteResult as _DeleteResult, RegisterResult as _RegisterResult, SessionToken as _SessionToken, Student as _Student, UpdateResult as _UpdateResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async adminLogin(arg0: string, arg1: string): Promise<AdminLoginResult> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0, arg1);
                return from_candid_AdminLoginResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0, arg1);
            return from_candid_AdminLoginResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUpdateStudent(arg0: SessionToken, arg1: string, arg2: UpdateProfileInput): Promise<UpdateResult> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateStudent(arg0, arg1, arg2);
                return from_candid_UpdateResult_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateStudent(arg0, arg1, arg2);
            return from_candid_UpdateResult_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteStudent(arg0: SessionToken, arg1: string): Promise<DeleteResult> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudent(arg0, arg1);
                return from_candid_DeleteResult_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudent(arg0, arg1);
            return from_candid_DeleteResult_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllStudents(arg0: SessionToken, arg1: bigint, arg2: bigint): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudents(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudents(arg0, arg1, arg2);
            return result;
        }
    }
    async getMyProfile(): Promise<Student | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerStudent(arg0: RegisterInput): Promise<RegisterResult> {
        if (this.processError) {
            try {
                const result = await this.actor.registerStudent(arg0);
                return from_candid_RegisterResult_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerStudent(arg0);
            return from_candid_RegisterResult_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchStudents(arg0: SessionToken, arg1: string): Promise<Array<Student>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchStudents(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchStudents(arg0, arg1);
            return result;
        }
    }
    async updateMyProfile(arg0: UpdateProfileInput): Promise<UpdateResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMyProfile(arg0);
                return from_candid_UpdateResult_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMyProfile(arg0);
            return from_candid_UpdateResult_n3(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AdminLoginResult_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminLoginResult): AdminLoginResult {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_DeleteResult_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeleteResult): DeleteResult {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_RegisterResult_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RegisterResult): RegisterResult {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_UpdateResult_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UpdateResult): UpdateResult {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Student]): Student | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _SessionToken;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: SessionToken;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Student;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Student;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
